services:
  docker-dind:
    image: docker:dind
    privileged: true
    ports:
      - "2377:2375"
      - "2378:2376"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    restart: always

  jenkins:
    build:
      context: .
    user: "0:0"  # Run as root to access Docker socket
    ports:
      - "8085:8080"
      - "50001:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    restart: always

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - jenkins
    restart: always


  # ============================================================================
  # MONITORING SERVICES COMMENTED OUT
  # These services are deployed with the application in docker/docker-compose.yml
  # to avoid port conflicts and ensure proper integration
  # ============================================================================
  #   grafana:
  #     image: grafana/grafana:latest
  #     ports:
  #       - "3000:3000"
  #     networks:
  #       - jenkins
  #     restart: always

  #   prometheus:
  #     image: prom/prometheus:latest
  #     ports:
  #       - "9090:9090"
  #     networks:
  #       - jenkins
  #     restart: always

  nexus:
    image: sonatype/nexus3:latest
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8082:8081"
    networks:
      - jenkins
    restart: always
  #   redis:
  #     image: redis:7-alpine
  #     container_name: school-management-redis
  #     ports:
  #       - "6379:6379"
  #     volumes:
  #       - redis_data:/data
  #     command: redis-server --appendonly yes
  #     restart: unless-stopped
  #     healthcheck:
  #       test: ["CMD", "redis-cli", "ping"]
  #       interval: 30s
  #       timeout: 10s
  #       retries: 3

volumes:
  jenkins_home:
  jenkins-docker-certs:
  nexus-data:
  sonarqube_data:
    # redis_data:

networks:
  jenkins:
    driver: bridge