-- Create all required enums
CREATE TYPE resource_type AS ENUM ('VIDEO', 'DOCUMENT', 'IMAGE', 'AUDIO', 'LINK');
CREATE TYPE room_type AS ENUM ('CLASSROOM', 'LABORATORY', 'AUDITORIUM', 'OFFICE', 'GYM');
CREATE TYPE grade_level AS ENUM ('KINDERGARTEN', 'ELEMENTARY', 'MIDDLE', 'HIGH', 'UNIVERSITY');
CREATE TYPE day_of_week AS ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY');
CREATE TYPE enrollment_status AS ENUM ('PENDING', 'ACTIVE', 'COMPLETED', 'DROPPED', 'SUSPENDED');
CREATE TYPE relation AS ENUM ('FATHER', 'MOTHER', 'GUARDIAN', 'SIBLING', 'OTHER');
CREATE TYPE contact_method AS ENUM ('EMAIL', 'PHONE', 'SMS', 'WHATSAPP', 'IN_PERSON');
CREATE TYPE staff_type AS ENUM ('ADMINISTRATIVE', 'MAINTENANCE', 'SECURITY', 'LIBRARIAN', 'COUNSELOR');
CREATE TYPE announcement_importance AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
CREATE TYPE audit_event_type AS ENUM (
    'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_STATUS_CHANGED',
    'COURSE_CREATED', 'COURSE_UPDATED', 'COURSE_DELETED',
    'CLASS_CREATED', 'CLASS_UPDATED', 'CLASS_DELETED',
    'ENROLLMENT_CREATED', 'ENROLLMENT_UPDATED', 'ENROLLMENT_DELETED',
    'GRADE_RECORDED', 'GRADE_UPDATED', 'GRADE_DELETED',
    'RESOURCE_UPLOADED', 'RESOURCE_UPDATED', 'RESOURCE_DELETED',
    'RESOURCE_COMMENT_ADDED', 'RESOURCE_COMMENT_DELETED',
    'TIMETABLE_UPDATED', 'ROOM_ASSIGNED', 'ROOM_CHANGED',
    'ANNOUNCEMENT_CREATED', 'ANNOUNCEMENT_UPDATED', 'ANNOUNCEMENT_DELETED',
    'LOGIN', 'LOGOUT', 'PASSWORD_CHANGED', 'PROFILE_UPDATED'
); 