package com.example.school_management.feature.operational.entity.enums;

public enum AuditEventType {
    USER_CREATED, USER_UPDATED, USER_DELETED, USER_STATUS_CHANGED,
    COURSE_CREATED, COURSE_UPDATED, COURSE_DELETED,
    CLASS_CREATED, CLASS_UPDATED, CLASS_DELETED,
    ENROLLMENT_CREATED, ENROLLMENT_UPDATED, ENROLLMENT_DELETED,
    GRADE_RECORDED, GRADE_UPDATED, GRADE_DELETED,
    RESOURCE_UPLOADED, RESOURCE_UPDATED, RESOURCE_DELETED,
    RESOURCE_COMMENT_ADDED, RESOURCE_COMMENT_DELETED,
    TIMETABLE_UPDATED, ROOM_ASSIGNED, ROOM_CHANGED,
    ANNOUNCEMENT_CREATED, ANNOUNCEMENT_UPDATED, ANNOUNCEMENT_DELETED,
    LOGIN, LOGOUT, PASSWORD_CHANGED, PROFILE_UPDATED
} 