global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'school-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'School Management Backend'
          environment: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'Prometheus'
          environment: 'production'

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          application: 'Grafana'
          environment: 'production'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          application: 'Loki'
          environment: 'production'
